version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:management-alpine
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234Abcd
      MYSQL_USER: test
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: 1234Abcd
